# Generated by Django 5.0.1 on 2024-02-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COWORKINGS', '0002_task_due_date_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
