# Generated by Django 5.0.1 on 2024-02-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COWORKINGS', '0005_remove_task_project_alter_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
